struct image_info {
	png_bytep image;
	png_colorp Pal8;
	png_bytep Trans;
	wchar_t* sType;
	size_t start_x;
	size_t start_y;
	size_t len_x;
	size_t len_y;
	size_t offset_x;
	size_t offset_y;
	unsigned __int32 colors;
	unsigned __int8 BGcolor;
};

extern struct image_info* decode_GL(FILE* pFi);
extern struct image_info* decode_GL3(FILE* pFi, int isGM3);
extern struct image_info* decode_X68R(FILE* pFi);
extern struct image_info* decode_VSP200l(FILE* pFi);
extern struct image_info* decode_VSP(FILE* pFi);
extern struct image_info* decode_X68T(FILE* pFi);
extern struct image_info* decode_X68V(FILE* pFi);
extern struct image_info* decode_VSP256(FILE* pFi);
extern struct image_info* decode_MSX_DRS(FILE* pFi);
extern struct image_info* decode_MSX_TT(FILE* pFi);
extern struct image_info* decode_MSX_GL(FILE* pFi);
extern struct image_info* decode_MSX_I(FILE* pFi);
extern struct image_info* decode_MSX_LV(FILE* pFi);
extern struct image_info* decode_MSX_LP(FILE* pFi);
extern struct image_info* decode_PMS8(FILE* pFi);
extern struct image_info* decode_PMS16(FILE* pFi);
extern void decode_d8(unsigned __int8* destination, unsigned __int8* source, size_t length, size_t Col_per_Row);
extern void decode_d16(unsigned __int16* destination, unsigned __int8* source, size_t length, size_t Col_per_Row);
extern void decode_d4_VSP(unsigned __int8* destination, unsigned __int8* source, size_t length, size_t Row_per_Col, size_t Cols, size_t planes);
